# Generated by Django 5.0.3 on 2024-03-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitedTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionId', models.CharField(max_length=100)),
                ('respondentId', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('toolName', models.CharField(max_length=100)),
                ('toolUrl', models.URLField(max_length=1000)),
                ('shortDescription', models.CharField(blank=True, null=True)),
                ('review', models.CharField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('lunchDate', models.DateTimeField(blank=True, null=True)),
                ('logoUrl', models.URLField(blank=True, max_length=1000, null=True)),
                ('priceModel', models.CharField(blank=True, max_length=100, null=True)),
                ('selectedTag', models.CharField(max_length=100)),
            ],
        ),
    ]
