# Generated by Django 5.0.3 on 2024-04-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careers', models.CharField(max_length=255)),
                ('main_categories', models.CharField(max_length=255)),
                ('sub_categories', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_domain', models.URLField(max_length=255)),
                ('sep', models.CharField(max_length=1)),
                ('platform', models.CharField(max_length=255)),
            ],
        ),
    ]
